#!/usr/bin/env python

from __future__ import print_function
import sys, getopt, os
from lxml import etree
import virl_utils

def usage(code):
    print('Usage: %s [-n node] [-f file] entry\n' % os.path.basename(__file__), file=sys.stderr)
    print('Prints out the requested value from a virl file.', file=sys.stderr)
    sys.exit(code)

def main(argv):
    file = '-'
    node = None
    try:
        opts, args = getopt.getopt(argv,'f:hn:',['file=','node='])
    except getopt.GetoptError:
        usage(1)
    for opt, arg in opts:
        if opt in ('-h', '--help'):
            usage(0)
        elif opt in ('-f','--file'):
            file = arg
        elif opt in ('-n','--node'):
            node = arg
    if len(args) != 1:
        usage(1)
    key = args[0]

    if node:
        try:
            value = virl_utils.get_file_node_entry_by_key(file, node, key)
            print(value)
        except virl_utils.NodeError as e:
            print('Error: ' + e.args[0], file=sys.stderr)
            exit(2)
        except virl_utils.EntryError as e:
            print('Error: ' + e.args[0], file=sys.stderr)
            exit(2)
    else:
        try:
            value = virl_utils.get_file_entry_by_key(file, key)
            print(value)
        except virl_utils.EntryError as e:
            print('Error: ' + e.args[0], file=sys.stderr)
            exit(2)

if __name__ == "__main__":
   main(sys.argv[1:])

# vim: tabstop=8 expandtab shiftwidth=4 softtabstop=4
