#!/usr/bin/env python

from __future__ import print_function
import sys, getopt, os, json

def usage(code):
    print('Usage: %s [-d] [-h] [-f file] key\n' % os.path.basename(__file__), file=sys.stderr)
    print('Return the value of a dict key', file=sys.stderr)
    sys.exit(code)
    
def main(argv):
    file = '-'
    port = '0'

    try:
        opts, args = getopt.getopt(argv,'dhf:',['--debug','--help','--file='])
    except getopt.GetoptError:
        usage(2)
    for opt, arg in opts:
        if opt in ("-d", "--debug"):
            debug += 1
        elif opt in ('-h', '--help'):
            usage(0)
        elif opt in ('-f', '--file'):
            file = arg
    keys = args
    if file == '-':
        f = sys.stdin
    else:
        f = open(file)

    data=eval(str(f.read()))

    for key in keys:
        if data[key]:
            print(data[key])

if __name__ == "__main__":
    main(sys.argv[1:])


# vim: tabstop=8 expandtab shiftwidth=4 softtabstop=4

