#!/usr/bin/env python

from __future__ import print_function
import sys, getopt, os, pprint

def usage(code):
    print('Usage: %s [-s subtype] [-f file]\n' % os.path.basename(__file__), file=sys.stderr)
    print('Lists all images.', file=sys.stderr)
    sys.exit(code)

def main(argv):
    file = '-'
    filtsubtype = None
    try:
        opts, args = getopt.getopt(argv,'f:hs:',['--help','--file=','--subtype='])
    except getopt.GetoptError:
        usage(1)
    for opt, arg in opts:
        if opt in ('-h', '--help'):
            usage(0)
        elif opt in ('-f','--file'):
            file = arg
        elif opt in ('-s','--subtype'):
            filtsubtype = arg
    keys = args

    if file == '-':
        f = sys.stdin
    else:
        f = open(file)
    data=eval(str(f.read()))

    images = data['images']
    for image in images:
        props = image['properties']
        id = image['id']
        release = props['release']
        subtype = props['subtype']
        if filtsubtype and filtsubtype != subtype:
            continue
        print('%s %s %s' % (id, subtype.replace(' ','_'), release))

if __name__ == "__main__":
   main(sys.argv[1:])

# vim: tabstop=8 expandtab shiftwidth=4 softtabstop=4
