#!/usr/bin/env python

from __future__ import print_function
import sys, getopt, os, pprint

def usage(code):
    print('Usage: %s -s subtype [-i srvimage|-f file|-u url] [-r release] [-v version]\n' % os.path.basename(__file__), file=sys.stderr)
    print('Ensure an image exists on the server', file=sys.stderr)
    sys.exit(code)

def main(argv):
    file = '-'
    filtsubtype = None
    try:
        opts, args = getopt.getopt(argv,'f:hi:r:s:u:v:',['--help','--file=','--image','--release','--subtype=','--url','--version'])
    except getopt.GetoptError:
        usage(1)
    for opt, arg in opts:
        if opt in ('-h', '--help'):
            usage(0)
        elif opt in ('-f','--file'):
            file = arg
        elif opt in ('-i','--image'):
            image = arg
        elif opt in ('-r','--release'):
            release = arg
        elif opt in ('-s','--subtype'):
            filtsubtype = arg
        elif opt in ('-u','--url'):
            url = arg
        elif opt in ('-v','--version'):
            version = arg

    if file == '-':
        f = sys.stdin
    else:
        f = open(file)
    data=eval(str(f.read()))

    images = data['images']
    for image in images:
        props = image['properties']
        subtype = props['subtype']
        if filtsubtype and filtsubtype != subtype:
            continue
        id = image['id']
        try:
            release = props['release']
            print('%s %s %s' % (id, subtype.replace(' ','_'), release))
        except:
            print('%s %s' % (id, subtype.replace(' ','_')))

if __name__ == "__main__":
   main(sys.argv[1:])

# vim: tabstop=8 expandtab shiftwidth=4 softtabstop=4
